#!/bin/bash
if [ -d "WORKSPACE" ]; then
  cd WORKSPACE/ADV_CPP_UTLS
else
  echo "cloning projects"
  mkdir WORKSPACE
  cd WORKSPACE
  git clone https://khanda89:mkhanda123@github.com/khanda89/ADV_CPP_UTLS.git
  cd ADV_CPP_UTLS
fi

if [ -f "app" ]; then
  echo "app exists."
else
  make
fi
./app
